# Generated by Django 5.2.5 on 2025-08-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='ref',
            field=models.CharField(blank=True, help_text='Reference id (e.g. INV-12, CRN-2, PO-5)', max_length=64),
        ),
    ]
