# Generated by Django 5.2.5 on 2025-09-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0002_product_barcode_product_tax_percent_sale_is_return_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_pos', 'Can use POS (sell/return)'), ('can_view_reports', 'Can view and download reports'), ('can_print_barcodes', 'Can print barcode labels'), ('can_adjust_stock', 'Can adjust stock (quick/bulk)'), ('can_manage_purchases', 'Can create purchases')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
