# Generated by Django 5.2.5 on 2025-09-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0003_apppermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_pos', 'Can use POS (sell/return)'), ('can_view_reports', 'Can view and download reports'), ('can_print_barcodes', 'Can print barcode labels'), ('can_adjust_stock', 'Can adjust stock (quick/bulk)'), ('can_manage_purchases', 'Can create purchases'), ('can_manage_users', 'Can manage users and roles')]},
        ),
    ]
