# Generated by Django 5.2.5 on 2025-09-01 15:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0004_alter_apppermission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(default='Your Store', max_length=120)),
                ('org_address', models.TextField(blank=True, default='')),
                ('org_phone', models.CharField(blank=True, default='', max_length=32)),
                ('org_email', models.EmailField(blank=True, default='', max_length=254)),
                ('bill_title', models.CharField(default='Tax Invoice', max_length=60)),
                ('bill_footer', models.CharField(blank=True, default='', max_length=200)),
                ('bill_tax_inclusive', models.BooleanField(default=True)),
                ('credit_enforce', models.BooleanField(default=False)),
                ('credit_alert_threshold', models.DecimalField(decimal_places=2, default=80, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_provider', models.CharField(choices=[('textlocal', 'Textlocal'), ('msg91', 'MSG91')], default='textlocal', max_length=20)),
                ('sms_api_key', models.CharField(blank=True, default='', max_length=200)),
                ('sms_sender', models.CharField(blank=True, default='TXTLCL', max_length=11)),
                ('call_enabled', models.BooleanField(default=False)),
                ('call_provider', models.CharField(choices=[('twilio', 'Twilio')], default='twilio', max_length=20)),
                ('call_sid', models.CharField(blank=True, default='', max_length=64)),
                ('call_token', models.CharField(blank=True, default='', max_length=64)),
                ('call_from', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'permissions': [('can_manage_settings', 'Can manage POS settings')],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='call_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posapp.sale')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
