# Generated by Django 5.2.5 on 2025-09-11 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0005_sitesetting_customer_call_opt_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='customerledger',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('other', 'Other')], default='cash', max_length=10),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['customer', 'date'], name='posapp_cust_custome_d257b5_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['sale'], name='posapp_cust_sale_id_27a2ba_idx'),
        ),
    ]
