# Generated by Django 5.2.5 on 2025-09-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0006_alter_customerledger_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_pos', 'Can use POS (sell/return)'), ('can_view_reports', 'Can view and download reports'), ('can_print_barcodes', 'Can print barcode labels'), ('can_adjust_stock', 'Can adjust stock (quick/bulk)'), ('can_manage_purchases', 'Can create purchases'), ('can_manage_settings', 'Can manage POS settings'), ('can_manage_users', 'Can manage users and roles'), ('can_credit_receive', 'Can receive customer payments'), ('can_credit_charge', 'Can post customer charges/fees'), ('can_credit_view', 'Can view customer credit statements')]},
        ),
    ]
