# Generated by Django 5.2.6 on 2026-05-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0008_productset_saleitem_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="details",
            field=models.TextField(blank=True),
        ),
    ]
