# Generated by Django 5.2.6 on 2026-05-08 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0009_saleitem_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="batch_no",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacture_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
