# Generated by Django 5.2.6 on 2026-06-21 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_tenant(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    Tenant = apps.get_model("posapp", "Tenant")
    TenantMembership = apps.get_model("posapp", "TenantMembership")

    users = list(User.objects.all())
    if not users:
        return

    tenant, _ = Tenant.objects.get_or_create(
        slug="default-store",
        defaults={
            "name": "Default Store",
            "owner_name": (
                f"{users[0].first_name} {users[0].last_name}".strip()
                or users[0].username
            ),
            "contact_email": users[0].email or "admin@example.com",
            "contact_phone": "",
            "address": "",
            "city": "",
            "state": "",
            "postal_code": "",
            "country": "India",
            "plan": "starter",
            "is_active": True,
        },
    )

    for user in users:
        TenantMembership.objects.get_or_create(
            tenant=tenant,
            user=user,
            defaults={
                "role": "owner" if user.is_superuser else "admin",
                "is_active": user.is_active,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0010_product_batch_no_product_expiry_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("owner_name", models.CharField(max_length=150)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=32)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=80)),
                ("state", models.CharField(max_length=80)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="India", max_length=80)),
                ("tax_id", models.CharField(blank=True, default="", max_length=32)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("growth", "Growth"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="posapp.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "role"], name="posapp_tena_tenant__62e59c_idx"
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="posapp_tena_user_id_48c70e_idx",
                    ),
                ],
                "unique_together": {("tenant", "user")},
            },
        ),
        migrations.RunPython(create_default_tenant, migrations.RunPython.noop),
    ]
