# Generated by Django 5.2.6 on 2026-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0011_tenant_tenantmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("retail_store", "Retail Store"),
                    ("wholesale", "Wholesale"),
                    ("pharmacy", "Pharmacy"),
                    ("restaurant", "Restaurant"),
                ],
                default="retail_store",
                max_length=20,
            ),
        ),
    ]
