# Generated by Django 5.2.6 on 2026-06-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0014_initialize_tenant_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="printer_type",
            field=models.CharField(
                choices=[
                    ("a4", "A4 / Normal Printer"),
                    ("thermal_80", "Thermal Receipt 80mm"),
                    ("thermal_58", "Thermal Receipt 58mm"),
                    ("label", "Barcode Label Printer"),
                ],
                default="a4",
                max_length=20,
            ),
        ),
    ]
