# Generated by Django 5.2.6 on 2026-06-21 13:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0015_sitesetting_printer_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("trial", "Free Trial"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("duration_days", models.PositiveIntegerField(default=30)),
                ("is_paid", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["price", "duration_days"],
            },
        ),
        migrations.AlterField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                choices=[
                    ("trial", "Free Trial"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("starter", "Starter"),
                    ("growth", "Growth"),
                    ("enterprise", "Enterprise"),
                ],
                default="starter",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionPaymentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("razorpay_order_id", models.CharField(max_length=120, unique=True)),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_orders",
                        to="posapp.tenant",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_orders",
                        to="posapp.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="posapp_subs_tenant__ee1755_idx",
                    ),
                    models.Index(
                        fields=["razorpay_order_id"],
                        name="posapp_subs_razorpa_b2b96c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="posapp.subscriptionplan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="posapp.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-ends_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "ends_at"],
                        name="posapp_tena_tenant__40ee5a_idx",
                    )
                ],
            },
        ),
    ]
