# Generated by Django 5.2.6 on 2026-06-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0016_subscriptionplan_alter_tenant_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="credit_limit",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="credit_alert_threshold",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="credit_enforce",
        ),
    ]
