# Generated by Django 5.2.13 on 2026-06-25 12:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0017_remove_customer_credit_limit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_no",
                    models.CharField(max_length=64, verbose_name="Batch number"),
                ),
                ("manufacture_date", models.DateField(verbose_name="Manufacture date")),
                ("expiry_date", models.DateField(verbose_name="Expiry date")),
                (
                    "purchase_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Purchase rate",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Sale price",
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="MRP",
                    ),
                ),
                (
                    "received_qty",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Received quantity",
                    ),
                ),
                (
                    "available_qty",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Available quantity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("empty", "Empty"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="posapp.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_batches",
                        to="posapp.supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_batches",
                        to="posapp.tenant",
                        verbose_name="Business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product batch",
                "verbose_name_plural": "Product batches",
                "ordering": ["expiry_date", "batch_no"],
                "indexes": [
                    models.Index(
                        fields=["tenant"], name="posapp_bat_tenant_1f413b_idx"
                    ),
                    models.Index(
                        fields=["product"], name="posapp_bat_product_17079d_idx"
                    ),
                    models.Index(
                        fields=["batch_no"], name="posapp_bat_batch_39a6e9_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="posapp_bat_expiry_8ec7df_idx"
                    ),
                    models.Index(
                        fields=["status"], name="posapp_bat_status_16aa98_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "product", "batch_no"),
                        name="uniq_tenant_product_batch_no",
                    )
                ],
            },
        ),
    ]
