# Generated by Django 5.2.13 on 2026-06-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0018_productbatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="product_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_items",
                to="posapp.productbatch",
            ),
        ),
    ]
