# Generated by Django 5.2.13 on 2026-07-01 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0019_purchaseitem_product_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="product_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_items",
                to="posapp.productbatch",
            ),
        ),
    ]
