# Generated by Django 5.2.13 on 2026-08-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0026_rename_biryani_rice_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product_images/%Y/%m/"
            ),
        ),
    ]
