# Generated by Django 5.2.13 on 2026-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0027_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="restaurant_menu_tax_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
