# Generated by Django 5.2.13 on 2026-09-08 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0030_kitchenorderticket_kot_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="order_status",
            field=models.CharField(
                choices=[("open", "Open"), ("paid", "Paid")],
                default="paid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="waiter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waiter_sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RestaurantTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                ("seats", models.PositiveIntegerField(default=4)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("occupied", "Occupied")],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_tables",
                        to="posapp.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="sale",
            name="restaurant_table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="posapp.restauranttable",
            ),
        ),
        migrations.AddIndex(
            model_name="restauranttable",
            index=models.Index(
                fields=["tenant", "status"], name="posapp_rt_tenant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restauranttable",
            index=models.Index(
                fields=["tenant", "is_active"], name="posapp_rt_tenant_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="restauranttable",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uniq_tenant_restaurant_table_name"
            ),
        ),
    ]
