# Generated by Django 5.2.6 on 2026-09-22 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posapp", "0033_tenantpaymentgateway_salepaymentorder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tenantmembership",
            unique_together={("tenant", "user")},
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="login_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="tenantmembership",
            unique_together={("tenant", "login_username"), ("tenant", "user")},
        ),
    ]
